// scripts/step1_transform_raw.js
// Run with: node scripts/step1_transform_raw.js

import { writeFileSync } from "node:fs";
import { movies as rawMovies } from "../src/movies.js";  // <-- YOUR ORIGINAL

function makeId(title, year) {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return year ? `${slug}-${year}` : slug;
}

function makeSortTitle(title) {
  return title.replace(/^(the|a|an)\s+/i, "").trim();
}

function toStructured(m) {
  const id = makeId(m.title, m.year);
  const sortTitle = makeSortTitle(m.title);

  return {
    id,
    title: m.title,
    sortTitle,
    year: m.year,

    collection: undefined,

    library: {
      format: m.format ?? "Unknown",
      owned: true,
      tags: []
    },

    metadata: {
      genres: Array.isArray(m.genres) ? m.genres : [],
      tmdbId: m.tmdbId,
      imdbId: undefined,
      runtimeMinutes: null,
      status: undefined,
      originalLanguage: undefined
    },

    media: {
      poster: null,
      backdrop: null,
      placeholder: m.image ?? null
    },

    text: {
      overview: undefined,
      tagline: undefined
    },

    ratings: {
      tmdb: {
        voteAverage: null,
        voteCount: null
      }
    },

    credits: {
      director: undefined,
      castPreview: []
    }
  };
}

const structured = rawMovies.map(toStructured);

const output = `// AUTO-GENERATED by step1_transform_raw.js
// Structured shell before TMDB enrichment.
export const movies = ${JSON.stringify(structured, null, 2)};
`;

writeFileSync("./movies.structured.js", output, "utf8");
console.log("Wrote movies.structured.js with", structured.length, "movies.");
