// scripts/updateTrailers.mjs
import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

// Adjust this path if your movies file is named differently
import { movies } from "../src/movies_with_category.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 🔑 TMDB API key: prefer VITE_TMDB_API_KEY, else take it from CLI arg
// Usage option 1: VITE_TMDB_API_KEY=xxx node scripts/updateTrailers.mjs
// Usage option 2: node scripts/updateTrailers.mjs xxx
const API_KEY = process.env.VITE_TMDB_API_KEY || process.argv[2];

if (!API_KEY) {
  console.error(
    "❌ TMDB API key is not set.\n" +
      "Set VITE_TMDB_API_KEY or pass it as an argument:\n" +
      "  VITE_TMDB_API_KEY=YOUR_KEY node scripts/updateTrailers.mjs\n" +
      "  node scripts/updateTrailers.mjs YOUR_KEY"
  );
  process.exit(1);
}

async function fetchYoutubeTrailerKey(tmdbId) {
  if (!tmdbId) return null;

  const url = `https://api.themoviedb.org/3/movie/${tmdbId}/videos?api_key=${API_KEY}`;

  try {
    const res = await fetch(url);
    if (!res.ok) {
      console.warn(
        `⚠️ TMDB videos request failed for tmdbId=${tmdbId}: ${res.status}`
      );
      return null;
    }

    const data = await res.json();
    const results = data?.results || [];
    if (!results.length) return null;

    // Prefer: official YouTube Trailer → any YouTube Trailer → any YouTube video
    const preferred =
      results.find(
        (v) =>
          v.site === "YouTube" &&
          v.type === "Trailer" &&
          v.official === true
      ) ||
      results.find((v) => v.site === "YouTube" && v.type === "Trailer") ||
      results.find((v) => v.site === "YouTube");

    return preferred?.key || null;
  } catch (err) {
    console.error(`❌ Error fetching videos for tmdbId=${tmdbId}`, err);
    return null;
  }
}

async function main() {
  console.log("🎬 Updating movies with YouTube trailer keys...");

  const updatedMovies = [];

  for (const movie of movies) {
    const tmdbId = movie.metadata?.tmdbId;

    if (!tmdbId) {
      // No TMDB id, just keep movie as-is
      updatedMovies.push(movie);
      continue;
    }

    console.log(`🔍 Fetching trailer for TMDB ID ${tmdbId} (${movie.title})...`);

    const existingKey = movie.metadata?.youtubeTrailerKey ?? null;
    const fetchedKey = await fetchYoutubeTrailerKey(tmdbId);
    const youtubeTrailerKey = fetchedKey || existingKey || null;

    if (youtubeTrailerKey) {
      console.log(`   ✅ Trailer key found: ${youtubeTrailerKey}`);
    } else {
      console.log("   ⚠️ No YouTube trailer found.");
    }

    const updated = {
      ...movie,
      metadata: {
        ...movie.metadata,
        youtubeTrailerKey,
      },
    };

    updatedMovies.push(updated);
  }

  // Write to a NEW file so you can verify before swapping
  const outPath = path.join(
    __dirname,
    "../src/movies_with_category_with_trailers.js"
  );

  const fileContents =
    "// Auto-generated by scripts/updateTrailers.mjs\n" +
    "export const movies = " +
    JSON.stringify(updatedMovies, null, 2) +
    ";\n";

  await fs.writeFile(outPath, fileContents, "utf8");

  console.log("✅ Done!");
  console.log(
    "➡️  Updated file written to src/movies_with_category_with_trailers.js"
  );
}

main().catch((err) => {
  console.error("❌ Fatal error in updateTrailers.mjs:", err);
  process.exit(1);
});
